let randomNumber = Math.floor(Math.random() * 10) + 1;
console.log(randomNumber);

function headerStyleChange() {
    const header = document.getElementById("header");
    header.innerHTML = " Ready for playing the game with me?";
    header.style.color = "red";
    header.style.fontSize = "50px";
}
function header2StyleChange() {
    const header2 = document.getElementById("header2");
    header2.innerHTML = "Guess the randon number generated by the computer.";
    header2.style.color = "green";
    header2.style.fontSize = "30px";
}
function header3StyleChange() {
    const header3 = document.getElementById("header3");
    header3.innerHTML = "Click one of the buttons 0-10 or enter a number in the input field.";
    header3.style.color = "green";
    header3.style.fontSize = "30px";
}
let buttonR = document.getElementById("Reset");
//let buttonS = document.getElementById("Start");//
let buttonP = document.getElementById("Play again");
let buttonF = document.getElementById("Feedback");


function saveInput() {

    let userInput = document.getElementById("inputField").value;
    button(userInput);
}

function Reset() {
    randomNumber = Math.floor(Math.random() * 10) + 1;
    console.log(randomNumber);
}

function button(i) {
    if (randomNumber == i) {
        document.getElementById("outputField").textContent = "You won!!! Try again ...";
        randomNumber = Math.floor(Math.random() * 10) + 1;
        console.log(randomNumber);

    } else if (randomNumber < i) {
        document.getElementById("outputField").textContent = "Too high";
    } else {
        document.getElementById("outputField").textContent = "Too low";
    };

}






